publish:
    docker:
        repo: mnbbrown/webproxy
	username: mnbbrown
	password: $$DOCKER_HUB_PASSWORD
        tag:
            - $$COMMIT
            - latest
        storage_driver: overlay

notify:
    slack:
        webhook_url: https://hooks.slack.com/services/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
        channel: devops
        username: drone
